<?php

function qr_code_theme($existing, $type, $theme, $path) {
  return [
    'qr_code_template' => [
      'variables' => [
        'image_data' => NULL,
      ],
    ],
  ];
}

/**
 * Preprocess qr_code_template.
 */
function qr_code_preprocess_qr_code_template(&$variables) {
  // add the drupal behavior to this page
  $variables['#attached']['library'][] = 'qr_code/js/qr_code.js';
  // $variables['#attached']['library'][] = 'qr_code.qr_code_behavior';
}
