<?php
use Drupal\menu_link_content\Entity\MenuLinkContent;

function qr_code_theme($existing, $type, $theme, $path) {
  return [
    'qr_code_template' => [
      'variables' => [
        'image_data' => NULL,
      ],
    ],
  ];
}

// preprocess qr-code-template.html.twig
function qr_code_preprocess_qr_code_template(&$variables) {;
  // add the image data to drupalSettings
  $variables['#attached']['drupalSettings']['qrCode']['imageData'] = $variables['image_data'];
}